-- Copy and paste this script into your Supabase SQL Editor and click "Run"

CREATE TABLE media (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "messageId" BIGINT UNIQUE NOT NULL,
  "mediaGroupId" TEXT,
  "fileId" TEXT NOT NULL,
  "fileUniqueId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "caption" TEXT,
  "mimeType" TEXT,
  "date" BIGINT NOT NULL,
  "size" BIGINT
);

-- Note: The column names are placed in quotes to match the exact casing of our JavaScript objects.
