-- Copy and paste this script into your Supabase SQL Editor and click "Run"

-- 1. Create Users Table
CREATE TABLE users (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" TEXT UNIQUE NOT NULL,
  "password" TEXT NOT NULL,
  "telegram_bot_token" TEXT,
  "telegram_chat_id" TEXT
);

-- 2. Create/Update Media Table
-- If you already have the media table, you can just add the column:
-- ALTER TABLE media ADD COLUMN user_id BIGINT REFERENCES users(id) ON DELETE CASCADE;

CREATE TABLE media (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "messageId" BIGINT UNIQUE NOT NULL,
  "mediaGroupId" TEXT,
  "fileId" TEXT NOT NULL,
  "fileUniqueId" TEXT NOT NULL,
  "type" TEXT NOT NULL,
  "caption" TEXT,
  "mimeType" TEXT,
  "date" BIGINT NOT NULL,
  "size" BIGINT
);

-- Note: The column names are placed in quotes to match the exact casing of our JavaScript objects.
